### ISSUE TITLE
Error while reviewing

### ISSUE THREAD

**Issue by OuraN2O** [Unlucky-Life/ankimon#90]
Hi ! 
A random error occured multiple times while reviewing cards : 
![image](https://github.com/Unlucky-Life/ankimon/assets/151692686/aceda2a4-a9d3-47dc-a6ee-3fea3ff91856)
It happens randomly, can't seem to find a pattern. I also couldn't reproduce it with your addon deactivated. Here's what shows up when anki is ran from the terminal : 
![image](https://github.com/Unlucky-Life/ankimon/assets/151692686/65842fb2-3298-4744-961d-ef5c893f00e3)

Anki version : 24.04.2 (a1fa865b), Qt6
OS : Archlinux kernel 6.8.7 with kde plasma 6 and x11 session
I'm running the 1.27 version of the addon (just tested and it also happens with the beta)

**Comment by face515** [comment]
Maybe switch discussion to problem #75, this could restart the discussion

**Comment by Unlucky-Life** [comment]
@OuraN2O @face515 this might be due to missing some back sprites (check in the github ankimon folder https://github.com/Unlucky-Life/ankimon/tree/008854b5b0554bfe7cfcb42c771270c43370fc40/missing_back_sprites and copy paste them in your ankimon addon folder under `user_files `=> `sprites` => `front_default`

**Comment by OuraN2O** [comment]
In front_default? You're sure ? Because it's back sprites copying to front so if I rewrite them the front sprits will be missing :thinking: . I copy pasted it in backsprites and it seems to work (for now ?)

**Comment by Unlucky-Life** [comment]
@OuraN2O ah i meant back_default ! Sorry !
Yes so either the issue is solved due to missing sprites. Or: its due to missing functions to certain types of attacks.

**Comment by OuraN2O** [comment]
Nevermind, it's not solved :sob: it just took some time to appear this time 
![image](https://github.com/Unlucky-Life/ankimon/assets/151692686/4853145d-a7bd-4692-8483-839e7a531f92)

**Comment by Unlucky-Life** [comment]
@OuraN2O jup then its the move issue :/ ..
